"""Turn the parcel CSV into seed.sql for the parcels table.

    python load.py path/to/parcel-sample-wake.csv > seed.sql

Blank cells become NULL. Every value is checked against the type its column needs, and
the script stops on the first one that does not fit rather than loading it.
"""

import csv
import re
import sys

# Must match normalize() in src/index.js, or typed addresses stop matching stored ones.
SUFFIXES = {
    "ROAD": "RD", "AVENUE": "AVE", "AV": "AVE", "STREET": "ST", "BOULEVARD": "BLVD",
    "BLV": "BLVD", "DRIVE": "DR", "LANE": "LN", "COURT": "CT", "PLACE": "PL",
    "PARKWAY": "PKWY", "HIGHWAY": "HWY", "CIRCLE": "CIR", "TRAIL": "TRL",
}


def normalize(address):
    text = re.sub(r"[^A-Z0-9 ]", " ", address.upper())
    return " ".join(SUFFIXES.get(w, w) for w in text.split())


def sql(value):
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + value.replace("'", "''") + "'"


def blank_to_none(v):
    v = v.strip()
    return v or None


def as_int(v, field, pin):
    v = blank_to_none(v)
    if v is None:
        return None
    if not re.fullmatch(r"\d+", v):
        sys.exit(f"pin {pin}: {field} is not a whole number: {v!r}")
    return int(v)


def main():
    rows = list(csv.DictReader(open(sys.argv[1], newline="", encoding="utf-8-sig")))
    keys = {}
    print("-- generated by load.py; do not edit by hand")
    for r in rows:
        pin = r["pin"].strip()
        key = normalize(r["site_address"])
        if key in keys:
            sys.exit(f"pins {keys[key]} and {pin} normalize to the same address {key!r}")
        keys[key] = pin
        acreage = float(r["acreage"])
        date = blank_to_none(r["last_sale_date"])
        if date and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
            sys.exit(f"pin {pin}: last_sale_date is not YYYY-MM-DD: {date!r}")
        values = [
            pin, r["site_address"].strip(), key, r["city"].strip().title(),
            r["zip"].strip(), blank_to_none(r["zoning"]), blank_to_none(r["land_use"]),
            acreage, as_int(r["heated_sqft"], "heated_sqft", pin),
            as_int(r["year_built"], "year_built", pin),
            as_int(r["assessed_value"], "assessed_value", pin), date,
            as_int(r["last_sale_price"], "last_sale_price", pin),
            r["tax_district"].strip(),
        ]
        print(
            "INSERT INTO parcels (pin, site_address, address_key, city, zip, zoning, "
            "land_use, acreage, heated_sqft, year_built, assessed_value, last_sale_date, "
            "last_sale_price, tax_district) VALUES ("
            + ", ".join(sql(v) for v in values) + ");"
        )
    print(f"-- {len(rows)} rows", file=sys.stderr)


if __name__ == "__main__":
    main()
